config/routes.rb
Rails.application.routes.draw do
  
 

  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to:'users#new', as: 'signup'
  get 'login', to:'sessions#new', as: 'login'
  get 'logout', to:'sessions#destroy', as: 'logout'
  
  resources :users
  
  get 'page/index'
  root 'page#index'
  get 'profile', to:'users#show', as: 'profile'

  resources :todolists

  

end

app/models/todolist.rb
class Todolist < ActiveRecord::Base

	scope :done, -> { where(done: true) }
	scope :pending, -> { where(done: false) }

	before_validation :init

	def init
		(self.done ||= false) || true
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
  				uniqueness: true,
  				format: {with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}
  validates :phone, presence: true
  def to_s
  	"#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	User.where(id: session[:user_id]).first
  end

  helper_method :current_user
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user=User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id]=user.id
  		redirect_to profile_path, notice: 'Logged In!'
  	else
      redirect_to login_path,  notice: "Wrong 'Email' or 'Password' !"
  	end
  end

  def destroy
  		session[:user_id]=nil
  		redirect_to root_url, notice: 'Logged Out!'
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def create
    @todolist=Todolist.new(todo_params)
    if @todolist.save!
      redirect_to todolists_path, notice: 'Item added!'
    else
      render "new", notice: @todolist.errors
    end
  end

  def show
  end

  def edit
  end

  def update
    @todolist=Todolist.find(params[:id])
    if @todolist.update_attribute(:done, true)
      redirect_to todolists_path, notice: "Todo item marked as done!"
    else
      redirect_to todolists_path, notice: "Todo item cannot be marked as done!"
    end
  end

  def new
    @todolist = Todolist.new
  end

  def destroy
    @todolist=Todolist.find(params[:id])
    @todolist.destroy

    redirect_to todolists_path, notice: "Todo item deleted!"
  end

  def index
    @todos = todolist.pending
    @todone = todolist.done
  end

  def todo_params
    params.require(:todolist).permit(:task, :duedate).tap do |p|
      p[:user_id] = current_user.id
    end
  end

  private

  def todolist
    Todolist.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
 
  def create
   @user = User.new(user_params)

    if @user.save
      session[:user_id]=@user.id
      redirect_to profile_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private
   
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :password, 
                                      :password_confirmation)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_header">
	<% if current_user %>
		Logged in as <%= current_user.email %>
		<%= link_to "Log Out", logout_path %>
	<% else %>
		<%= link_to "Sign Up", signup_path %>
		<%= link_to "Log In", login_path %>
	<% end %>
</div>

<% flash.each do |key, value| %>
	<%= content_tag(:div, class: "alert alert-#{key}") do %>
	<p><%= value %></p>
	<% end %>
	<% end %> 
<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<h1>Todo App</h1>
<p>Please Log In or Signup to continue!</p>

app/views/todolists/create.html.erb
<h1>Todolists#create</h1>
<p>Find me in app/views/todolists/create.html.erb</p>

app/views/todolists/destroy.html.erb
<h1>Todolists#destroy</h1>
<p>Find me in app/views/todolists/destroy.html.erb</p>

app/views/todolists/edit.html.erb
<h1>Todolists#edit</h1>
<p>Find me in app/views/todolists/edit.html.erb</p>

app/views/todolists/index.html.erb
<h2> Todo Items</h2>

<% @todos.each do |t| %>
<table>
	<tr>
		<th>Task</th>
		<th>Due Date</th>
		<th>Action</th>
	</tr>
	<tr>
		<td><%= t.task %></td>
		<td><%= t.duedate %></td>
		<td><%= link_to "Mark as Done", todolist_path(t), :method => :put %></td>
	</tr>
</table>
<% end %>

<h2>Done List</h2>
<% @todone.each do |t| %>
<table>
	<tr>
		<th>Task</th>
		<th>Due Date</th>
		<th>Action</th>
	</tr>
	<tr>
		<td><%= t.task %></td>
		<td><%= t.duedate %></td>
		<td><%= link_to "Remove", t, :confirm => "Are you sure?", :method => :delete %></td>
	</tr>
</table>
<% end %>
<p><%= link_to "Add new Item", new_todolist_path %></p>

app/views/todolists/new.html.erb
<h1>Add new Item</h1>
<%= form_for @todolist do |f| %>
	<%= f.label :task %>: <%= f.text_field :task %>
	<%= f.label :duedate %>: <%= f.date_select(:duedate, :order => [:month, :day, :year]) %>
	<%= f.submit "Add to list" %>
<% end %>

app/views/todolists/show.html.erb
<h1>Todolists#show</h1>
<p>Find me in app/views/todolists/show.html.erb</p>

app/views/todolists/update.html.erb
<h1>Todolists#update</h1>
<p>Find me in app/views/todolists/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
       <!-- <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% user=User.find_by_email(params[:email]) %>
<h3>Hello <%= current_user.first_name%>,</h3>
<p>Your profile...</p>
<p>
  <strong>Name:</strong>
  <%= current_user.first_name %> <%= current_user.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= current_user.email %>
</p>
<p>
  <strong>Phone:</strong>
  <%= current_user.phone %>
</p>
<%= link_to 'Manage ToDo(s)', todolists_path %>